config/routes.rb
Rails.application.routes.draw do
  get 'credit_cards/new'
  devise_for :users
  get 'items/index'
  root 'items#index'
  get 'items/new'
  resources:users, only: [:show, :edit, :update] do
    get :favorites, on: :collection
    get :listed_items, on: :collection
    get :purchased_items, on: :collection
  end
  
  resources:credit_cards, only: [:new, :show] do
    collection do
      post 'show', to: 'credit_cards#show'
      post 'pay', to: 'credit_cards#pay'
      post 'delete', to: 'credit_cards#delete'
    end
  end 

  resources:items do
    resource :favorites, only: [:create, :destroy]
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    member do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'transactions/buy'
      get 'transactions/done'
    end
  end
end

app/models/credit_card.rb
class CreditCard < ApplicationRecord
  belongs_to :user

  with_options presence: true do
    validates :card_id
    validates :customer_id
  end

  with_options uniqueness: true do
    validates :card_id
    validates :customer_id
  end

end

app/controllers/credit_cards_controller.rb
class CreditCardsController < ApplicationController
  require "payjp"

  def new
    credit_card = CreditCard.where(user_id: current_user.id)
    redirect_to action: "show" if credit_card.exists?
  end

  def pay
    Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]

    if params['payjp-token'].blank?
      redirect_to action: "new"
    else
      customer = Payjp::Customer.create(card: params['payjp-token']) 
      @credit_card = CreditCard.new(
      user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card
      )

      if @credit_card.save
        redirect_to action: "show"
      else
        redirect_to action: "pay"
      end
    end
  end

  def delete 
    credit_card = CreditCard.where(user_id: current_user.id).first
    if credit_card.blank?
    else
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(credit_card.customer_id)
      customer.delete
      credit_card.delete
    end
      redirect_to action: "new"
  end

  def show 
    credit_card = CreditCard.where(user_id: current_user.id).first
    if credit_card.blank?
      redirect_to action: "new" 
    else
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(credit_card.customer_id)
      @default_credit_card_information = customer.cards.retrieve(credit_card.card_id)
    end
  end

end

app/helpers/credit_cards_helper.rb
module CreditCardsHelper
end

app/views/credit_cards/new.html.haml
.Flex.Center.Base
  .Card-Container
    .Header
      = image_tag "material/logo/logo.png", alt: "フリマロゴ", class: 'logo'
    .Card-main
      .Input-box
        %h2.Input-box__title クレジットカード情報入力

        // クレカ情報入力フォーム
        = form_with url: pay_credit_cards_path, html: { name: "inputForm" }, id: 'charge-form', method: :post do |f|
        
          .Input-box__field

            // カード番号入力
            .Input-box__input-form
              = f.label :カード番号 ,class: 'Input-box__input-form--title'
              %span.Input-box__input-form--require 必須
              %br/
              = f.text_field :number, class: 'Input-box__input-form--form', placeholder: '  半角数字のみ', maxlength:"16", id: "card_number", type: "text"
            .Input-box__card-image
              = image_tag "material/logo/visa-logo.png", alt: "visa", class: 'card-logo'
              = image_tag "material/logo/mastercard-logo.png", alt: "mastercard", class: 'card-logo'
              = image_tag "material/logo/amex-logo.gif", alt: "amex", class: 'card-logo'
              = image_tag "material/logo/jcb-logo.gif", alt: "jcb", class: 'card-logo'
              = image_tag "material/logo/dinersclub-logo.png", alt: "dinersclub", class: 'card-logo'
              = image_tag "material/logo/discover_logo.jpg", alt: "discover", class: 'card-logo'

            // 有効期限入力
            .Input-box__input-form
              = f.label :有効期限 ,class: 'Input-box__input-form--title'
              %span.Input-box__input-form--require 必須
              %br/
              .Input-box__input-form--efective-date
                = f.select :exp_month, [["01", 1], ["02", 2], ["03", 3], ["04", 4], ["05", 5], ["06", 6], ["07", 7], ["08", 8], ["09", 9], ["10", 10], ["11", 11], ["12", 12]], {}, class: 'Input-box__input-form--pulldown', type: "text"
                %span 月
                = f.select :exp_year, [["20", 2020], ["21", 2021], ["22", 2022], ["23", 2023], ["24", 2024], ["25", 2025], ["26", 2026], ["27", 2027], ["28", 2028], ["29", 2029], ["30", 2030]], {}, class: 'Input-box__input-form--pulldown', type: "text"
                %span 年

              // cvc入力
              .Input-box__input-form
              = f.label :セキュリティコード ,class: 'Input-box__input-form--title'
              %span.Input-box__input-form--require 必須
              %br/
              = f.text_field :cvc, class: 'Input-box__input-form--form', placeholder: '  カード裏面4桁もしくは3桁の番号', maxlength:"4", type: "text"

            #card_token

            // 情報送信ボタン
            .actions
              = f.submit "登録する", class: 'Input-box__submit-btn', id: "token_submit"


    .Footer
      = image_tag "material/logo/logo.png", alt: "フリマロゴ", class: 'logo'
      .Footer__text © FURIMA

app/views/credit_cards/show.html.haml
.Flex.Center.Base
  .Card-Container
    .Header
      = image_tag "material/logo/logo.png", alt: "フリマロゴ", class: 'logo'
    .Card-box
      .Card-info
        %h2.Card-info__title 登録クレジットカード情報
        %br
        .Card-info__card-box
          .Card-info__card-box--card-number
            = "**** **** **** " + @default_credit_card_information.last4
            %br
          .Card-info__card-box--card-exp
            - exp_month = @default_credit_card_information.exp_month.to_s
            - exp_year = @default_credit_card_information.exp_year.to_s.slice(2,3)
            = exp_month + " / " + exp_year
        
        .Card-info__btns
          = form_tag(delete_credit_cards_path, method: :post, id: 'charge-form',  name: "inputForm" ) do
            %input{ type: "hidden", name: "card_id", value: ""}
            %button.Card-info__btns--delete-btn 削除する

          = link_to user_path(current_user.id),class: "Card-info__btns--mypage-btn" do
            マイページに戻る

    .Footer
      = image_tag "material/logo/logo.png", alt: "フリマロゴ", class: 'logo'
      .Footer__text © FURIMA