config/routes.rb
Rails.application.routes.draw do
  get 'credit_cards/new'
  devise_for :users
  get 'items/index'
  root 'items#index'
  get 'items/new'
  resources:users, only: [:show, :edit, :update] do
    get :favorites, on: :collection
    get :listed_items, on: :collection
    get :purchased_items, on: :collection
  end
  
  resources:credit_cards, only: [:new, :show] do
    collection do
      post 'show', to: 'credit_cards#show'
      post 'pay', to: 'credit_cards#pay'
      post 'delete', to: 'credit_cards#delete'
    end
  end 

  resources:items do
    resource :favorites, only: [:create, :destroy]
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    member do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'transactions/buy'
      get 'transactions/done'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_one :address, dependent: :destroy
  has_one :credit_card
  has_many :favorites, dependent: :destroy
  accepts_nested_attributes_for :address

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable

  validates :nickname,         presence: true, uniqueness: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email,            presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }
  validates :password,         presence: true, length: { in: 7..127 }, confirmation: true
  VALID_NAME_REGEX = /\A[ぁ-んァ-ン一-龥]/
  validates :family_name,      presence: true, format: { with: VALID_NAME_REGEX }
  validates :first_name,       presence: true, format: { with: VALID_NAME_REGEX }
  VALID_KANA_REGEX = /\A[ァ-ヶー－]+\z/
  validates :family_name_kana, presence: true, format: { with: VALID_KANA_REGEX }
  validates :first_name_kana,  presence: true, format: { with: VALID_KANA_REGEX }
  validates :birthday,         presence: true
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
    @user = User.new(address_params)
    @user.build_address
    @user.save
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  def destroy
    super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  def cancel
    super
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    super(resource)
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    super(resource)
  end

  private

  def address_params
    params.permit(:sign_up, keys: [:nickname, :family_name, :first_name, :family_name_kana, :first_name_kana, :birthday, address_attributes: [:family_name, :first_name, :family_name_kana, :first_name_kana, :postcode, :prefecture, :city, :block, :building_name, :phone_number]])
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show 
    @user = User.find(params[:id])
    favorites = Favorite.where(user_id: current_user.id).pluck(:item_id)
    @favorite_list = Item.find(favorites)
  end

  def edit
  end

  def favorites
    favorites = Favorite.where(user_id: current_user.id).pluck(:item_id)
    @favorite_list = Item.find(favorites)
  end

  def listed_items
    @listed_items = Item.where(user_id: current_user.id)
  end

  def purchased_items
    @purchased_items = Item.where(buyer_id: current_user.id)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.haml
.Flex.Center.Base
  .Edit-Container
    .Header
      = image_tag "material/logo/logo.png", alt: "フリマロゴ", class: 'logo'
    .Main
      = link_to "ログアウト",destroy_user_session_path, method: :delete, class: "log-out"
        
    .Footer
      = image_tag "material/logo/logo.png", alt: "フリマロゴ", class: 'logo'
      .Footer__text © FURIMA

app/views/users/favorites.html.haml
= render "items/header"
- breadcrumb :favorite
= render "layouts/breadcrumbs"
.main-search
  %section.mypage-picupContents
    .favorite-title お気に入り一覧
    .newBox
      .listed_items
        - if @favorite_list.present?
          - @favorite_list.each do |item|
            .newList
              = link_to item_path(item.id), class: "beef" do
                %figure.newList--image
                  - item.images.first(1).each do |image|
                    = image_tag image, class: "meat"
                .newList--body
                  %h3.name
                    = item.name
                  .details
                    %ul
                      %li.foodPrice
                        = item.price
                      %li.star
                    .priceFurima
                      (税込）

= render "items/footer"
= render "items/putup-btn" 

app/views/users/listed_items.html.haml
.show-container
  = render "items/header"
  - breadcrumb :listed_items
  = render "layouts/breadcrumbs"
  .mypage-picupContents
    .listed-title 出品した商品一覧
    .listed_items
      - @listed_items.each do |item|
        .newList
          = link_to item_path(item.id), class: "beef" do
            %figure.newList--image
              - item.images.first(1).each do |image|
                = image_tag image, class: "meat"
            .newList--body
              %h3.name
                = item.name
              .details
                %ul
                  %li.foodPrice
                    = item.price
                  %li.star
                .priceFurima
                  (税込）
  = render "items/footer"
  = render "items/putup-btn" 

app/views/users/purchased_items.html.haml
.show-container
  = render "items/header"
  - breadcrumb :purchased_items
  = render "layouts/breadcrumbs"
  .mypage-picupContents
    .listed-title 購入した商品一覧
    .listed_items
      - @purchased_items.each do |item|
        .newList
          = link_to item_path(item.id), class: "beef" do
            %figure.newList--image
              - item.images.first(1).each do |image|
                = image_tag image, class: "meat"
            .newList--body
              %h3.name
                = item.name
              .details
                %ul
                  %li.foodPrice
                    = item.price
                  %li.star
                .priceFurima
                  (税込）
  = render "items/footer"
  = render "items/putup-btn" 

app/views/users/show.html.haml
.show-container
  = render "items/header"
  - breadcrumb :mypage
  = render "layouts/breadcrumbs"
  .show-main
    .sidebar
      .menu
        %h2.menu__title マイページメニュー
        .menu__list
          %ul
            = link_to favorites_users_path, class:"menu__list--btn" do
              %li お気に入り一覧
      .menu
        %h2.menu__title 商品を出品・購入
        .menu__list
          %ul
            = link_to new_item_path, class:"menu__list--btn" do
              %li 商品を出品する
            = link_to listed_items_users_path, class:"menu__list--btn" do
              %li 出品した商品
            = link_to purchased_items_users_path, class:"menu__list--btn" do
              %li 購入した商品
      .menu
        %h2.menu__title 設定・その他
        .menu__list
          %ul
            = link_to "#", class:"menu__list--btn" do
              %li 設定
            = link_to credit_cards_new_path, class:"menu__list--btn" do
              %li クレジットカード登録・変更
            = link_to edit_user_path , class:"menu__list--btn" do
              %li ログアウト
    .content
      .user-nickname
        = current_user.nickname
        さんのマイページ
      .content__title
        重要なお知らせ
      .content__detail
        開発中です！！
  = render "items/footer"
  = render "items/putup-btn"