config/routes.rb
Rails.application.routes.draw do
  get 'credit_cards/new'
  devise_for :users
  get 'items/index'
  root 'items#index'
  get 'items/new'
  resources:users, only: [:show, :edit, :update] do
    get :favorites, on: :collection
    get :listed_items, on: :collection
    get :purchased_items, on: :collection
  end
  
  resources:credit_cards, only: [:new, :show] do
    collection do
      post 'show', to: 'credit_cards#show'
      post 'pay', to: 'credit_cards#pay'
      post 'delete', to: 'credit_cards#delete'
    end
  end 

  resources:items do
    resource :favorites, only: [:create, :destroy]
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    member do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'transactions/buy'
      get 'transactions/done'
    end
  end
end

app/models/item.rb
class Item < ApplicationRecord
  has_many_attached :images
  belongs_to :user, optional: true
  has_many :favorites, dependent: :destroy 
  belongs_to :category
  
  with_options presence: true do
    validates :name
    validates :description
    validates :status
    validates :freight
    validates :shipment_source
    validates :ship_date
    validates :price
    validates :images
    validates :user_id
    validates :category_id
  end

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
  
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :move_to_index, except: [:index, :show]
  before_action :set_item, only: [:show, :destroy, :edit, :update]
  before_action :set_category, only: [:new, :edit, :create, :update, :destroy]

  def index
    @items = Item.limit(5).order("id DESC")
    @categories = Category.all
    @favorites = Favorite.all
  end

  def move_to_index
    unless user_signed_in?
      redirect_to action: :index
    end
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path, notice: '出品が完了しました'
    else
      redirect_to new_item_path, alert: '必須項目を入力してください'
    end
  end

  def show
    @related_items = Item.limit(3).where(category: @item.category_id).
      where.not(id: @item.id).order("RAND()", "id DESC")
    @category_id = @item.category_id
    @category_grandchild = Category.find(@category_id)
    @category_child = @category_grandchild.parent
    @category_parent = @category_child.parent
  end

  def destroy
    if @item.destroy
      redirect_to root_path, notice: '商品を削除しました'
    else
      redirect_to item_path(@item.id), alert: 'エラーが発生しました'
    end
  end

  def edit
    grandchild_category = @item.category
    child_category = grandchild_category.parent
    parent_category = child_category.parent
    @category_parent_array = Category.where(ancestry: parent_category.ancestry)
    @category_children_array = Category.where(ancestry: child_category.ancestry)
    @category_grandchildren_array = Category.where(ancestry: grandchild_category.ancestry)

    if user_signed_in? && current_user.id == @item.user_id && @item.buyer_id.blank?
      render :edit
    else
      redirect_to root_path
    end
  end

  def update
    @item.category_id = 'nil'
    edit_images
    if @item.images.length <= 10 && @item.images.length > 0
      if @item.update(update_params)
        redirect_to item_path(@item.id), notice: '編集が完了しました'
      else
        redirect_to edit_item_path, alert: '必須項目を入力してください'
      end
    else
      redirect_to edit_item_path, alert: '画像は1枚以上10枚以下です'
    end
  end

  def get_category_children
    @category_children = Category.find(params[:parent_name]).children
  end

  def get_category_grandchildren
    @category_grandchildren = Category.find("#{params[:child_id]}").children
  end

  private
  def set_category  
    @category_parent_array = Category.where(ancestry: nil)
  end

  def item_params
    params.require(:item).permit(:name, :description, :status, :freight, :shipment_source, :ship_date, :price, :brand, :size, :buyer_id, :category_id, images: []).merge(user_id: current_user.id)
  end

  def update_params
    params.require(:item).permit(:name, :description, :status, :freight, :shipment_source, :ship_date, :price, :brand, :size, :buyer_id, :category_id)
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def edit_images
    delete_images
    add_images
  end

  def delete_images
    if params[:item][:image_ids]
      params[:item][:image_ids].each do |image_id|
        image = @item.images.find(image_id)
        image.purge
      end
    end
    
    if params[:item][:replace_images]
      params[:item][:replace_images].each do |image_id|
        image = @item.images.find(image_id)
        image.purge
      end
    end
  end

  def add_images
    if (params[:item][:images]).presence
      @item.images.attach(params[:item][:images])
    end

    if params[:item][:replace_images]
      params[:item][:replace_images].each do |num|
        @item.images.attach(params[:item][:"replace_image_#{num}"])
      end
    end
  end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_footer.html.haml
.footer
  .footer__image
    = image_tag "material/pict/bg-appBanner-pict.jpg", alt: "footer-image", class:"footer__image"
    .footer__message
      だれでもかんたん、人生を変えるフリマアプリ
      %h2 今すぐ無料ダウンロード！
    = link_to "#", class:"footer__btn" do
      = image_tag "material/logo/App_Store_Badge_US.svg", alt: "AppStore", class:"AppStore-logo"
    = link_to "#", class:"footer__btn" do
      = image_tag "material/logo/google-play-badge.png", alt: "googleplay", class:"googleplay-logo"
  %ul.footer__contents
    %li.footer__contents--left
      %h2 FURIMAについて
      %ul.footer__content
        %li
          = link_to "#", class:"footer__btn" do
            会社概要（運営会社）
        %li
          = link_to "#", class:"footer__btn" do
            プライバシーポリシー
        %li
          = link_to "#", class:"footer__btn" do
            FURIMA利用規約
        %li
          = link_to "#", class:"footer__btn" do
            ポイントに関する特約
    %li.footer__contents--center 
      %h2 FURIMAを見る
      %ul.footer__content
        %li
          = link_to "#", class:"footer__btn" do
            カテゴリー一覧
        %li
          = link_to "#", class:"footer__btn" do
            ブランド一覧
    %li.footer__contents--right
      %h2 ヘルプ＆ガイド
      %ul.footer__content
        %li
          = link_to "#", class:"footer__btn" do
            FURIMAガイド
        %li
          = link_to "#", class:"footer__btn" do
            FURIMAロゴ利用ガイドライン
        %li
          = link_to "#", class:"footer__btn" do
            お知らせ
  = link_to "/", class:"root__btn" do
    = image_tag "material/logo/logo-white.png", alt: "フリマロゴ", class: 'footer-logo'
  ©︎FURIMA

app/views/items/_header.html.haml
.header
  .header__top
    .header__logo
      = link_to "/", class:"root__btn" do
        = image_tag "material/logo/logo.png", alt: "フリマロゴ", class: 'logo'
    .header__index
      .index-form
        = form_with url: search_items_path, method: :get, class: "search-form", local: true do |f|
          = f.text_field :keyword, placeholder:"キーワードから探す", class: "search-input"
          %button.index-btn
            = image_tag "material/icon/icon-search 1.png", alt: "フリマロゴ", class: 'search-logo'
  .header__menu
    .header__menu--left
      = link_to "#", class:"menu__list--btn" do
        カテゴリ
      = link_to "#", class:"menu__list--btn" do
        ブランド
    %ul.header__menu--right
      - if user_signed_in?
        = link_to user_path(current_user.id),class: "menu__list--btn" do
          マイページ
      - else
        %li
          = link_to new_user_session_path, class:"menu__list--btn" do
            ログイン
        %li
          = link_to new_user_registration_path, class:"menu__list--btn" do
            新規会員登録

app/views/items/_putup-btn.html.haml
= link_to new_item_path do
    .putup-btn
        %span 出品する
        = image_tag 'material/icon/icon_camera.png', alt: '出品マーク', height: '54px', width: '54px', class: 'putup-image'

app/views/items/_sold-label-S.html.haml
.sold-label-S
  .sold-label-S__title
    SOLD

app/views/items/edit.html.haml
.Flex.Center.Base
  .Container
    .Header
      = image_tag "material/logo/logo.png", alt: "フリマロゴ", class: "logo"
    .Sell-main
      .sell-box
        = form_with model: @item, local: true do |f|
          .sell-box__sell-form
            .sell-box__edit-title 商品を編集してください
            .sell-box__image-frame
              .sell-box__image-frame__title
                出品画像
                %span.sell-box__require 必須
              .sell-box__image-frame__guide 最大10枚までアップロードできます
              %input{name: "item_images_length", type: "hidden", value: @item.images.length, class: 'item_images_length'}/
              .edit-preview
                - @item.images.each do |image|
                  .item-image-edit
                    .item-image-edit__content
                      = image_tag image, class: "item-image-edit__content--icon", width: "114px", height: "76px", id: "preview_#{image.id}"
                      = f.check_box :image_ids, {multiple: true}, image.id, false
                      %label.delete_check_box(for="item_image_ids_#{image.id}") 削除
                      = f.check_box :replace_images, {multiple: true}, image.id, false
                      %label.edit-btn{data: {index: image.id}} 編集
              #image-box-1
                .item-num-0#image-box__container
                  .sell-box__upload
                    .sell-box__upload__image
                      = f.label :images ,class: "sell-box__upload__add-image" do
                        = icon('fas','camera', class: "camera-icon")
                        = f.file_field :images, multiple: true,type: 'file', value:"",class: "Hidden"
                - @item.images.each do |image|
                  = f.file_field :"replace_image_#{image.id}", {data: {index: image.id}, id: "item_replace_image_#{image.id}", style: "display: none;"}
            .sell-box__item
              .sell-box__item__title-area
              .sell-box__item__name
                = f.label :商品名 ,class: "sell-box__item__name"
                %span.sell-box__require 必須
                %br
                = f.text_field :name, class: "sell-box__item__form", placeholder: "40文字まで", maxlength:"40"
              .sell-box__item__description
                = f.label :商品の説明 ,class: "sell-box__item__description"
                %span.sell-box__require 必須
                %br
                = f.text_area :description, class: "sell-box__item__description-form", placeholder: "商品の説明（必須 1,000文字以内） &#13;&#10;（色、素材、重さ、定価、注意点など） &#13;&#10; &#13;&#10;例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。".html_safe, maxlength:"1000"
                .sell-box__item__word-counter
                  %span.numerator 0
                  %span.denominator /1000
            .sell-box__detail
              .sell-box__detail__title 商品詳細
              .sell-box__detail__category
                = f.label :カテゴリー ,class: "sell-box__detail__category"
                %span.sell-box__require 必須
                %br
                .item_input__body__category#category_box
                  .pulldown#partent_box
                    = f.select :parent_id, options_for_select( @category_parent_array.map{|c| [c[:name], c[:id]]},@item.category.parent.parent.id), {}, { class: "parent_category_box", id: "parent_category"}
                  .pulldown.item_input__body__category__children#children_box
                    = f.select :children_category, options_for_select(@category_children_array.map{|b| [b.name, b.id, {data:{category: b.id}}]}, {prompt: "指定なし", selected: @item.category.parent.id}),{}, {class: 'item_input__body__category__children--select', id: 'children_category'}
                  .pulldown.item_input__body__category__grandchildren#grandchildren_box
                    = f.select :category_id, options_for_select(@category_grandchildren_array.map{|b| [b.name, b.id, {data:{category: b.id}}]}, {prompt: "指定なし", selected: @item.category.id}),{}, {class: 'item_input__body__category__grandchildren--select', id: 'grandchildren_category', name:"item[category_id]"}
                .sell-box__detail__size
                = f.label :サイズ ,class: "sell-box__detai__size"
                %span.sell-box__require--any 任意
                %br
                = f.select :size ,[["選択してください", ""],["XXS以下", "XXS以下"], ["XS(SS)", "XS(SS)"], ["S", "S"], ["M", "M"], ["L", "L"], ["XL(LL)", "XL(LL)"], ["2XL(3L)", "2XL(3L)"], ["3XL(4L)", "3XL(4L)"], ["4XL(5L)", "4XL(5L)"], ["FREE SIZE", "FREE SIZE"]], {},class: "sell-box__detail__form"
              .sell-box__detail__brand
                = f.label :ブランド ,class: "sell-box__detail__brand"
                %span.sell-box__require--any 任意
                %br
                = f.text_field :brand ,class: "sell-box__detail__form", placeholder: " 例）シャネル"
              .sell-box__detail__status
                = f.label :商品の状態 ,class: "sell-box__detail__status"
                %span.sell-box__require 必須
                %br
                = f.select :status ,[["選択してください", ""],["新品、未使用", "新品、未使用"], ["未使用に近い", "未使用に近い"], ["目立った傷や汚れなし", "目立った傷や汚れなし"], ["やや傷や汚れあり", "やや傷や汚れあり"], ["傷や汚れあり", "傷や汚れあり"], ["全体的に状態が悪い", "全体的に状態が悪い"]], {},class: "sell-box__detail__form"
            .sell-box__freight
              %h3.sell-box__freight__title 配送について
              .sell-box__freight__charge
                = f.label :配送料の負担 ,class: "sell-box__freigt__charge"
                %span.sell-box__require 必須
                %br
                = f.select :freight ,[["選択してください", ""],["送料込み(出品者負担)", "送料込み(出品者負担)"], ["着払い(購入者負担)", "着払い(購入者負担)"]], {},class: "sell-box__freight__form"
              .sell-box__freight__shipment-source
                = f.label :配送元の地域 ,class: "sell-box__freigt__shipment-source"
                %span.sell-box__require 必須
                %br
                = f.collection_select :shipment_source, Prefecture.all, :id, :name, {} ,class: "sell-box__freight__form"
              .sell-box__freight__ship-date
                = f.label :発送までの日数 ,class: "sell-box__freigt__ship-date"
                %span.sell-box__require 必須
                %br
                = f.select :ship_date ,[["選択してください", ""],["1~2日で発送", "1~2日で発送"], ["2~3日で発送", "2~3日で発送"], ["4~7日で発送", "4~7日で発送"]], {},class: "sell-box__freight__form"
            .sell-box__price
              %h3.sell-box__price__title 価格（¥300〜9,999,999）
              .sell-box__price-area
                = f.label :販売価格 ,class: "sell-box__price-area__selling-price"
                .sell-box__price-area__price-require 必須
                .sell-box__price-area__yen ￥
                = f.text_field :price, class: "sell-box__price-area__form", placeholder: " 0"
              .sell-box__commission
                .sell-box__commission__text 販売手数料（10％）
                .sell-box__commission__sum ー
              .sell-box__profit
                .sell-box__profit__text 販売利益
                .sell-box__profit__sum ー
            .sell-box__actions
              = f.submit "編集を確定する",class: 'sell-box__actions__submit-btn'
              %br
              - if @item.images.length <= 10 && @item.images.length > 0
                = link_to item_path,class: "sell-box__actions__back-btn" do
                  キャンセル
          .warning
            .warning__text
              禁止されている行為および出品物を必ずご確認ください。
              偽ブランド品や盗品物などの販売は犯罪であり、
              法律により処罰される可能性があります。 
              また、出品をもちまして加盟店規約に同意したことになります。

    .Footer
      = image_tag "material/logo/logo.png", alt: "フリマロゴ", class: "logo"
      .Foote__text © FURIMA 

app/views/items/index.html.haml
= render "items/header"
.main
  %section.mainView
    .viewMain
      .maincontent
        %h2.maincontent__subtitle
          %br
            人生を変えるフリマアプリ
        .priceFurima.maincontent__text
          FURIMAはだれでも簡単に出品・購入できる
          %brフリマアプリです
        .maincontent__btn
          = link_to "#", class: "aMain" do
            = image_tag 'material/pict/bn_app_store.png', class: "appPict", alt: "リンゴ"
          = link_to "#", class: "bMain" do
            = image_tag 'material/pict/google-play-badge .png', class: "googlePict", alt: "グーグル"
  %section.topReason
    %h2.subMenu
      FURIMAが選ばれる３つの理由
    .contents
      .secondContent
        .contentPict
          %span.number
            1
          = image_tag 'material/pict/pict-reason-01.jpg', class: "listingPict", alt: "出品"
        %h3.contentText
          %span 3分
          ですぐに出品
        .priceFurima.contentManner
          スマホで入力するだけですぐに出品できる！
      .secondContent
        .contentPict
          %span.number
            2
          = image_tag 'material/pict/pict-reason-02.jpg', class: "listingPict", alt: "シンプル"
        %h3.contentText
          %span シンプル
          で使いやすい
        .priceFurima.contentManner
          めんどくさい入力は必要なく、検索も購入もスムーズ！
      .secondContent
        .contentPict
          %span.number
            3
          = image_tag 'material/pict/pict-reason-03.jpg', class: "listingPict", alt: "手数料"
        %h3.contentText
          手数料
          %span業界最安
        .priceFurima.contentManner
          最大3％でお得に出品＆購入！
  %section.thirdMenu
    .thirdMenu__inner
      %h2.subManner
        会員数日本一位
      .priceFurima.text
        FURIMAは、フリマアプリで最も人気。
        %br
        出品・購入も業界最多です！
        %br
        ほしかったあの商品に出会えるかもしれません。
      .btn
        = link_to "#", class: "aMain" do
          = image_tag 'material/pict/bn_app_store.png', class: "appPict", alt: "リンゴ"
        = link_to "#", class: "bMain" do
          = image_tag 'material/pict/google-play-badge .png', class: "googlePict", alt: "グーグル"
  %section.furimaFuture
    %h2.center
      FURIMAの特徴
    .menus
      %section.childMenu
        %figure.furimaImage
          = image_tag 'material/icon/icon-01.png', class: "men", alt: "男性"
        %h3.menu__subtitle
          簡単に売り買いできる
        .priceFurima.menu__detail
          スマホひとつで、いつでもどこでも簡単に出品・購入が可能！
      %section.childMenu
        %figure.furimaImage
          = image_tag 'material/icon/icon-03.png', class: "woman", alt: "女性"
        %h3.menu__subtitle
          売上金は即日振り込みに対応
        .priceFurima.menu__detail
          午前9時までに振り込みを依頼いただければ、翌日に指定の口座に入金いたします！
      %section.childMenu
        %figure.furimaImage
          = image_tag 'material/icon/icon-04.png', class: "card", alt: "カード"
        %h3.menu__subtitle
          様々な支払いに対応
        .priceFurima.menu__detail
          お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。
  %section.picupContents
    %h2.top
      ピックアップカテゴリー
    .newBox
      .newTop
        = link_to "#", class: "newPost" do
          %h3.title
            新規投稿商品
      .newLists
        - @items.each do |item|
          .newList
            = link_to item_path(item.id), class: "beef" do
              %figure.newList--image
                - item.images.first(1).each do |image|
                  = image_tag image, class: "meat"
                  -if item.buyer_id.present?
                    = render "items/sold-label-S"
              .newList--body
                %h3.name
                  = item.name
                .details
                  %ul
                    %li.foodPrice
                      = item.price
                    %li.star
                      %i.fas.fa-star
                        = item.favorites.count
                  .priceFurima
                    (税込）
  %section.picupContents
    %h2.top
      ピックアップブランド
    .newBox
      .newTop
        = link_to "#", class: "brand" do
          %h3.title
            アーカイバ
      .newLists
        - @items.where(brand: 'apple').each do |item|
          .newList
            = link_to item_path(item.id), class: "beef" do
              %figure.newList--image
                - item.images.first(1).each do |image|
                  = image_tag image, class: "meat"
                  -if item.buyer_id.present?
                    = render "items/sold-label-S"
              .newList--body
                %h3.name
                  = item.name
                .details
                  %ul
                    %li.foodPrice
                      = item.price
                    %li.star
                      %i.fas.fa-star
                        = item.favorites.count
                  .priceFurima
                    (税込）

  = render "items/footer"
  = render "items/putup-btn"

app/views/items/search.html.haml
= render "items/header"
.main-search
  %section.picupContents
    .newBox
      .newLists
        - @items.each do |item|
          .newList
            = link_to item_path(item.id), class: "beef" do
              %figure.newList--image
                - item.images.first(1).each do |image|
                  = image_tag image, class: "meat"
              .newList--body
                %h3.name
                  = item.name
                .details
                  %ul
                    %li.foodPrice
                      = item.price
                    %li.star
                  .priceFurima
                    (税込）

  = render "items/footer"
  = render "items/putup-btn"

app/views/items/show.html.haml
= render "items/header"
.main
  .showMain
    .topContent
      .itemBox
        %h2.itemBox__name
          = @item.name
        .itemBox__body
          .image_first
            - @item.images.first(1).each do |image|
              = image_tag image, alt: "商品画像", class: "img_1"
              -if @item.buyer_id.present?
                .sold-label-L
                  .sold-label-L__title
                    SOLD
              .image_list
                -@item.images.each do |image|
                  = image_tag image, alt:"商品画像", class: "images"
        .itemBox__price 
          ￥
          = @item.price
          円
          .itemBox__price_detail
            %span (税込)
            %span.show-freight
              = @item.freight
        .itemDetail 
          = @item.description
        .table
          %table
            %tbody
              %tr
                %th 出品者
                %td
                  = @item.user.nickname
              %tr
                %th カテゴリー
                %td 
                  = link_to "#", class:"table_link" do
                    = @category_parent.name
                  %br
                  = link_to "#", class:"table_link" do
                    = @category_child.name
                  %br
                  = link_to "#", class:"table_link" do
                    = @category_grandchild.name
              %tr
                %th ブランド
                %td
                  = @item.brand
              %tr
                %th 商品のサイズ
                %td
                  = @item.size
              %tr
                %th 商品の状態
                %td 
                  = @item.status
              %tr 
                %th 配送料の負担
                %td 
                  = @item.freight
              %tr 
                %th 発送元の地域
                %td 
                  = link_to "#", class:"table_link" do
                    = @item.shipment_source
              %tr 
                %th 発送日の目安
                %td
                  = @item.ship_date
        - if user_signed_in? && current_user.id != @item.user_id
          = link_to '商品購入画面へ進む', transactions_buy_item_path, class: "buy-btn" 
        - unless user_signed_in?
          = link_to '商品購入画面へ進む', new_user_registration_path, class: "buy-btn"
        .optionalArea
          %ul 
            %li.likeBtn
              = render "favorites/favorite"
          %ul.optional
            %li.optionalBtn
              = link_to "#" do
                = icon('fas', 'flag')
                不適切な商品の通報
      .commentBox
        %ul.commentContents
        %form.new_comment{id:"new_comment", action:"#", charaset:"UTF-8", method:"post"}
          %textarea.textarea{id:"comment_body"}
          .show_noticeMsg 
            相手のことを考え丁寧なコメントを心がけましょう。
            %br 
            不快な言葉遣いなどは利用制限や退会処分となる事があります。
          %button.commentBtn{type: "submit"}
            = link_to "#" do
              = icon('fas', 'comment')
              コメントする
      - if user_signed_in? && current_user.id == @item.user_id && @item.buyer_id.blank?
        .seller_function
          = link_to '商品を編集する', edit_item_path(@item.id), class:"edit-item"
          = link_to '商品を削除する', item_path, method: :delete, data: { confirm: '本当に削除しますか？' }, class: "delete-item"
    %ul.links 
      %li 
        = link_to "#", class:"link" do
          = icon('fas', 'angle-left')
          前の商品
      %li 
        = link_to "#", class:"link" do
          後ろの商品
          = icon('fas','angle-right')

    .relatedItems
      .relatedItem
      = link_to item_path, class: "relatedItems_bar" do
        = @item.category.name
        をもっと見る
      .relatedBox
        - @related_items.each do |item|
          = link_to item_path(item.id), class:"productList" do
            .relatedProduct
              - item.images.first(1).each do |image|
                = image_tag image, class:"productList_image"
                -if item.buyer_id.present?
                  = render "items/sold-label-S"
                .productList_body
                  %h3.name 
                    = item.name
                  .details
                    %ul 
                      %li 
                        = item.price
                        円
                      %li 
                        = icon('fas','star')
                        = item.favorites.count
                    (税込)
  = render "items/footer"
  = render "items/putup-btn" 