config/routes.rb
Rails.application.routes.draw do
  get 'credit_cards/new'
  devise_for :users
  get 'items/index'
  root 'items#index'
  get 'items/new'
  resources:users, only: [:show, :edit, :update] do
    get :favorites, on: :collection
    get :listed_items, on: :collection
    get :purchased_items, on: :collection
  end
  
  resources:credit_cards, only: [:new, :show] do
    collection do
      post 'show', to: 'credit_cards#show'
      post 'pay', to: 'credit_cards#pay'
      post 'delete', to: 'credit_cards#delete'
    end
  end 

  resources:items do
    resource :favorites, only: [:create, :destroy]
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    member do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'transactions/buy'
      get 'transactions/done'
    end
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_item
  before_action :move_to_index

  def buy
    credit_card = CreditCard.where(user_id: current_user.id).first
    if credit_card.blank?
    else
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(credit_card.customer_id)
      @default_credit_card_information = customer.cards.retrieve(credit_card.card_id)
    end
  end

  def done
    unless request.referer&.include?("/buy")
      redirect_to action: :buy
    else
      card = current_user.credit_card
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      Payjp::Charge.create(
      amount: @item.price, 
      customer: card.customer_id, 
      currency: 'jpy', 
      )
      if @item.update(buyer_id: current_user.id)
        flash[:notice] = '購入しました。'
      else
        flash[:alert] = '購入に失敗しました。'
        redirect_to controller: "transactions", action: 'buy'
      end
    end
  end



  private

  def set_item
    @item = Item.find(params[:id])
  end

  def move_to_index
    if @item.buyer_id.present?
      redirect_to root_path
    end
  end

end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/buy.html.haml
.Flex.Center.Base
  .Container
    .Header
      = image_tag "material/logo/logo.png", alt: "フリマロゴ", class: 'logo'
    .Main
      .purchase-box
        %h2.purchase-box__title 購入内容の確認
        .purchase-box__item-frame
          .detail
            .detail__image
              - @item.images.first(1).each do |image|
                = image_tag image, alt: "商品画像", class: 'item-image'
            .detail__item
              %h3.detail__item__name 
                = @item.name
              .total-cost
                .total-cost__price 
                  = @item.freight
                .total-cost__en ￥
                .total-cost__sum 
                  = @item.price
        .purchase-box__payment
          .payment-area
            %h4.payment-area__title 支払い金額
            .payment-area__total-cost
              .payment-area__total-cost__yen ￥
              .payment-area__total-cost__sum 
                = @item.price
        .purchase-box__payment-method
          .credit-card
            - if current_user.credit_card.nil?
              .credit-card__before-registration
                %h5.credit-card__before-registration__title 支払い方法
                = link_to new_credit_card_path do
                  = icon('fas', 'plus-circle')
                  登録してください
            - else
              .credit-card__registration
                %h5.credit-card__registration__title 支払い方法
                = link_to new_user_registration_path do
                  変更する
                  = icon('fas', 'angle-right')
              .credit-card__infometion
                .credit-card__infometion__text クレジットカード
                .credit-card__infometion__number 
                  = "**** **** **** " + @default_credit_card_information.last4
                - exp_month = @default_credit_card_information.exp_month.to_s
                - exp_year = @default_credit_card_information.exp_year.to_s.slice(2,3)
                .credit-card__infometion__expiration 
                  = "有効期限 " + exp_month + " / " + exp_year
                = image_tag "material/logo_visa.png", alt: "カードロゴ", class: 'card-logo'
            
        .purchase-box__address
          .current-address
            .current-address__registration
              %h6.delivery-address__registration__title 配送先
              = link_to new_user_registration_path do
                変更する
                = icon('fas', 'angle-right')
            .delivery-address
              .delivery-address__postcode 
                = "〒" + current_user.address.postcode.first(3) + "-" + current_user.address.postcode.last(4)
              .delivery-address__text
                = current_user.address.prefecture + current_user.address.city + current_user.address.block + current_user.address.building_name
              .delivery-address__name 
                = current_user.address.family_name + " " + current_user.address.first_name
        .purchase-box__decision
          .decision-area
            - if current_user.credit_card.nil?
              %button.decision-area__no-btn 購入する

            - else
              = link_to transactions_done_item_path, class: "decision-area__btn" do
                %button.decision-area__btn 購入する
    .Footer
      = image_tag "material/logo/logo.png", alt: "フリマロゴ", class: 'logo'
      .Footer__text © FURIMA 

app/views/transactions/done.html.haml
.Flex.Center.Base
  .Container
    .Header
      = image_tag "material/logo/logo.png", alt: "フリマロゴ", class: 'logo'
    .Main
      .purchase-done
        .purchase-done__item-frame
          .detail-done
            .detail-done__image
              - @item.images.first(1).each do |image|
                = image_tag image, alt: "商品画像", class: 'done-item-image'
            %p.detail-done__title 購入が完了しました！
        .purchase-done__name-frame
          .title-done 
            = @item.name
        .purchase-done__cos-frame
          .cost-done
            .cost-done__price 
              = @item.freight
            .cost-done__yen ￥
            .cost-done__sum 
              = @item.price
        .purchase-done__decision-frame
          .decision-done
            = link_to root_path, class: "decision-done__btn" do
              %button.decision-done__btn トップページへ戻る
    .Footer
      = image_tag "material/logo/logo.png", alt: "フリマロゴ", class: 'logo'
      .Footer__text © FURIMA 